# Generated by Django 3.1.3 on 2020-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.URLField(default=True, max_length=1024, null=True),
        ),
    ]
